run:
	/home/mj/.jdks/corretto-11.0.20.1/bin/java -javaagent:/snap/intellij-idea-community/456/lib/idea_rt.jar=40905:/snap/intellij-idea-community/456/bin -Dfile.encoding=UTF-8 -classpath /home/mj/Black-Jack/BlackJack/target/classes black.jack.Main
